
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 30 19:11:35 COT 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Class = 16;
  public static final int Incremento = 22;
  public static final int Coma = 9;
  public static final int If = 12;
  public static final int Void = 34;
  public static final int LlaveC = 7;
  public static final int Static = 33;
  public static final int Decremento = 23;
  public static final int Package = 14;
  public static final int LlaveA = 6;
  public static final int Else = 13;
  public static final int string = 11;
  public static final int OperadorAritmetico = 21;
  public static final int Asignacion = 24;
  public static final int ParentecisC = 4;
  public static final int Booleano = 30;
  public static final int ParentecisA = 3;
  public static final int Relacionales = 25;
  public static final int Return = 17;
  public static final int While = 19;
  public static final int FinalLinea = 5;
  public static final int For = 20;
  public static final int EOF = 0;
  public static final int CorcheteC = 32;
  public static final int OperadorLogico = 26;
  public static final int error = 1;
  public static final int CorcheteA = 31;
  public static final int Private = 35;
  public static final int Linea = 2;
  public static final int ERROR = 37;
  public static final int Do = 18;
  public static final int Public = 15;
  public static final int Atribucion = 29;
  public static final int Identificador = 27;
  public static final int Numero = 28;
  public static final int TipoDato = 10;
  public static final int Main = 36;
  public static final int Comillas = 8;
}

