/* Generated By:JavaCC: Do not edit this line. compConstants.java */
package semantico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int INCR = 6;
  /** RegularExpression Id. */
  int DECR = 7;
  /** RegularExpression Id. */
  int PUBLIC = 8;
  /** RegularExpression Id. */
  int PRIVATE = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int IMPORT = 11;
  /** RegularExpression Id. */
  int PATH_LIB = 12;
  /** RegularExpression Id. */
  int STATIC = 13;
  /** RegularExpression Id. */
  int VOID = 14;
  /** RegularExpression Id. */
  int MAIN = 15;
  /** RegularExpression Id. */
  int PROGRAMA = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int ELSEIF = 19;
  /** RegularExpression Id. */
  int FOR = 20;
  /** RegularExpression Id. */
  int SWITCH = 21;
  /** RegularExpression Id. */
  int CASE = 22;
  /** RegularExpression Id. */
  int BREAK = 23;
  /** RegularExpression Id. */
  int DEFAUL = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int WRITE = 27;
  /** RegularExpression Id. */
  int READ = 28;
  /** RegularExpression Id. */
  int LPAREN = 29;
  /** RegularExpression Id. */
  int RPAREN = 30;
  /** RegularExpression Id. */
  int LBRACE = 31;
  /** RegularExpression Id. */
  int RBRACE = 32;
  /** RegularExpression Id. */
  int LBRACKET = 33;
  /** RegularExpression Id. */
  int RBRACKET = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int DOT = 37;
  /** RegularExpression Id. */
  int DOUBLECOMMA = 38;
  /** RegularExpression Id. */
  int EQ = 39;
  /** RegularExpression Id. */
  int LE = 40;
  /** RegularExpression Id. */
  int MN = 41;
  /** RegularExpression Id. */
  int GE = 42;
  /** RegularExpression Id. */
  int GR = 43;
  /** RegularExpression Id. */
  int NE = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int AND = 46;
  /** RegularExpression Id. */
  int INT = 47;
  /** RegularExpression Id. */
  int DEC = 48;
  /** RegularExpression Id. */
  int CHR = 49;
  /** RegularExpression Id. */
  int STR = 50;
  /** RegularExpression Id. */
  int NUMBER = 51;
  /** RegularExpression Id. */
  int IDENTIFIER = 52;
  /** RegularExpression Id. */
  int DECIMAL = 53;
  /** RegularExpression Id. */
  int CADENA = 54;
  /** RegularExpression Id. */
  int CARAC = 55;
  /** RegularExpression Id. */
  int DOUBLEPOINT = 56;
  /** RegularExpression Id. */
  int STRARRAY = 57;
  /** RegularExpression Id. */
  int STRING_LIST = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"++\"",
    "\"--\"",
    "\"public\"",
    "\"private\"",
    "\"class\"",
    "\"import\"",
    "<PATH_LIB>",
    "\"static\"",
    "\"void\"",
    "\"public static void main (String[] args)\"",
    "\"package\"",
    "\"if\"",
    "\"else\"",
    "\"if else\"",
    "\"for\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\"default\"",
    "\"do\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"ileer\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "\"==\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"int\"",
    "\"double\"",
    "\"char\"",
    "\"String\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<DECIMAL>",
    "<CADENA>",
    "<CARAC>",
    "\":\"",
    "\"String[]\"",
    "<STRING_LIST>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
